# Generated by Django 2.1.5 on 2021-11-02 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(related_name='product', to=settings.AUTH_USER_MODEL),
        ),
    ]
