# Generated by Django 2.1.5 on 2021-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211102_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
