# Generated by Django 2.1.5 on 2021-11-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_gst_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hsn',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='selling_price',
        ),
    ]
